@host = http://localhost:5000


###  Get categories
get {{host}}/categories/

### Create category
post {{host}}/categories/
Content-Type: application/json

{
    "name": "Main"
}

### Update category by id
put {{host}}/categories/60f798d23e48ed1933043b61
Content-Type: application/json

{
    "name": "Drinks"
}

### Delete category by id
delete {{host}}/categories/60fbb0540deddc060ef4ba1e
