@host = http://localhost:5000


### Get items
get {{host}}/items/

### Get item
get {{host}}/items/60f6e7f247ed8c300a443363

### Create item
post {{host}}/items/
Content-Type: application/json

{
    "name": "Chicken Karage (8pc)",
    "published": true,
    "unitPrice": 8.5,
    "description": "Japnese style fried Chicken",
    "category": "60f6cdcb3907ff237c7bf42c"
}

### Update item by id
put {{host}}/items/60f6f3789dfca33baa0e1d06
Content-Type: application/json

{
    "name": "Kon Ramen",
    "published": true,
    "unitPrice": 14.50,
    "category": "60f6cdb83907ff237c7bf42a",
    "description" : "Kon Ramen is our signiture ramen /nIt has our unique soup base"
}

### Delete item by id
delete {{host}}/items/60f787cfe0ec4815956a1593
