@host = http://localhost:5000

### Get orders
get {{host}}/orders/

### Get order by id
get {{host}}/orders/

### Create order
post {{host}}/order/
Content-Type: application/json

{
    "completed": false,
    "takeAway": true,
    "instruction": "i am hungry af",
    "orderItems": [
        {
            "orderItem": "60f6e7f247ed8c300a443363",
            "qty": 3
        },
        {
            "orderItem": "60f6f3c59dfca33baa0e1d0d",
            "qty": 2
        }
    ],
    "subCost": 30.2
}

### Delete order by id
delete {{host}}/orders/60f7a7a2e9a525231c4013a5